name: "cooper4"
server:
  port: 8080
#spring
spring:
  profiles.active: DEVELOP
  thymeleaf:
    cache: false
#JDBC
jdbc:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.99.182:3306/cooper4
  username: root
  password: root
  pool:
    initialSize: 10
    maxActive: 100
    maxWait: 60000
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 25200000
    removeAbandoned: true
    removeAbandonedTimeout: 7200
    logAbandoned: true
    poolPreparedStatements: false

#RABBIT_MQ
rebbitmq:
  queue:
  exchange:
  route:
  rl:
    username:
    password:
    host:
    port:
    virtualHost:
  lc:
    concurrency:
    maxConcurrency:
    prefetch:
    method:
#DRDID
druid:
  stat:
    slowSqlMillis: 3000
    logSlowSql: true
    mergeSql: true
  log:
    resultSetLogEnabled: false
    dataSourceLogEnabled: true
#Redis
redis:
  pool:
    maxIdle: 200
    minIdle: 1
    maxWait: 10000
    testOnBorrow: true
    testOnReturn: true
  rl:
    host: "localhost"
    port: 6379
    timeout: 10000
    password: ""

# MyBatis
mybatis:
  mapperLocations: "classpath:/org/freda/sqlmaps/**/*.xml"
  mapperConfig: 'classpath:/org.freda/mybatis/mybatis-config.xml'

# Mongo
mongo:
  host: 127.0.0.1
  port: 27017
  username:
  password:
  database: xx

